
images:
- name: hello
  newName: gcr.io/kuba-linux-polska/go-hello-world
  newTag: 74646c78102e9ba10f1d6b70250995dcdccac6da

configMapGenerator:
- literals:
  - APP_VERSION=1.0.0
  - APP_ENVIRONMENT=test
  name: env-vars
  namespace: hello-world
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/
