
images:
- name: hello
  newName: gcr.io/kuba-linux-polska/go-hello-world
  newTag: af556757320d8de22771c8f2dc8765638204df73

configMapGenerator:
- literals:
  - APP_VERSION=1.0.0
  - APP_ENVIRONMENT=test
  name: env-vars
  namespace: hello-world
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/
