
images:
- name: hello
  newName: gcr.io/kuba-linux-polska/go-hello-world
  newTag: 8d79c179951bf1578c6d0aac024c2aadfd8b86fd


configMapGenerator:
- literals:
  - APP_VERSION=1.0.0
  - APP_ENVIRONMENT=test
  name: env-vars
  namespace: hello-world
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/
