apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    run: hello-world
    lang: go
    team: awesome
  namespace: hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello-world
