---
name: Deploy app to K8S pipeline - DEV

on:
  push:
    branches:
      - dev

env:
  APP_NAME: "go-hello-world"
  CLUSTER_NAME: "gke-dev"
  CLUSTER_ZONE: "europe-west3-a"

jobs:

  deploy-to-test:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.0.4"
      - run: cd k8s-infra-and-objects && git checkout dev
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: install kubectl
        uses: azure/setup-kubectl@v1
      - name: config cluster
        run: gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE
      - name: Update the cluster
        run: cd k8s-infra-and-objects && kustomize build dev | kubectl apply -f -
